# Generated by Django 5.1.6 on 2025-03-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
